### ISSUE TITLE
Add rules_cc to federation

### ISSUE THREAD

**Issue by Yannic** [abseil/federation-head#10]
Starting with https://github.com/abseil/abseil-cpp/pull/351, abseil depends on https://github.com/bazelbuild/rules_cc. It would be good to include this to the federation.

I would submit a PR, but I'm not sure how @absl-federation-github is involved, so I'll leave this for someone familiar with that bot.

**Comment by gennadiycivil** [comment]
Should be good now please check

**Comment by Yannic** [comment]
Yes, thank you!

Submitted #15 to pin the rules to specific commits instead of consuming them directly from head.
